### ISSUE TITLE
Bug Report: AWS does not recognize already downloaded files in HTTP

### ISSUE THREAD

**Issue by hwd15508** [nidata/nidata#68]
I used `hcp/example1.py` with `fetcher_type='http'` to download some data. Then, I switched to `fetcher_type='aws'`, and re-ran the example.

**Expected:**
The files would not be re-downloaded; they should be in the file cache.

**Current behavior:**
The files were re-downloaded using AWS.

**Notes:**
I did not try downloading through AWS, then seeing if they're found in the cache.

**Comment by bcipolli** [comment]
I just ran AWS twice, and it looks like the AWS fetcher is not checking the cache.

**Comment by bcipolli** [comment]
Fixed in 6cbee1fa7f053f40dce92f9ad93132d9e69aec27 ; thanks!
